use std::collections::BTreeSet;
use std::fs;
use std::io::{BufRead, BufReader, Write as _};
use std::net::{Ipv4Addr, Ipv6Addr};
use std::os::unix::fs::PermissionsExt as _;
use std::os::unix::process::CommandExt as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};

use argvus_control_center_core::config::AppConfig;

use super::{host, keyboard, locale, time};

const ELEVATED_ENV: &str = "ARGVUS_SYSTEM_SETTINGS_ELEVATED";
const LOCALE_GEN: &str = "/etc/locale.gen";
const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_BACKUP: &str = "/etc/resolv.conf.argvus-backup";
const RESOLV_MARKER: &str = "# Generated by ARGVUS Control Center";

pub fn run(args: &[String]) -> Result<(), String> {
  validate_args(args)?;
  ensure_root(args)?;
  match args {
    [area, action, value] if area == "timezone" && action == "set" => {
      run_command("timedatectl", &["set-timezone", value])
    }
    [area, action, value] if area == "hostname" && action == "set" => {
      host::validate_hostname(value)?;
      run_command("hostnamectl", &["set-hostname", value])
    }
    [area, action, value] if area == "datetime" && action == "ntp" => {
      run_command("timedatectl", &["set-ntp", value])
    }
    [area, action, value] if area == "datetime" && action == "set" => {
      run_command("timedatectl", &["set-time", value])
    }
    [area, action, value] if area == "locale" && action == "set-lang" => {
      run_command("localectl", &["set-locale", &format!("LANG={value}")])
    }
    [area, action, values @ ..] if area == "locale" && action == "set-generated" => {
      set_generated_locales(values)
    }
    [area, action, layout] if area == "keyboard" && action == "layout" => {
      run_command("localectl", &["set-x11-keymap", layout])
    }
    [area, action, layout, variant] if area == "keyboard" && action == "variant" => {
      run_command("localectl", &["set-x11-keymap", layout, "", variant])
    }
    [area, action, keymap] if area == "keyboard" && action == "console-keymap" => {
      run_command("localectl", &["set-keymap", keymap])
    }
    [area, action, unit] if area == "service" => {
      let args = service_args(action, unit)?;
      run_command(
        "systemctl",
        &args.iter().map(String::as_str).collect::<Vec<_>>(),
      )
    }
    [area, action, governor] if area == "governor" && action == "set" => set_governor(governor),
    [area, action, values @ ..] if area == "power" => run_power(action, values),
    [area, action, values @ ..] if area == "boot" => run_boot(action, values),
    [area, action, values @ ..] if area == "package" => run_package(action, values),
    [area, action, values @ ..] if area == "network" => run_network(action, values),
    [area, action, value] if area == "config" && action == "icons" => set_appearance_icons(value),
    _ => Err("unsupported system-settings command".to_string()),
  }
}

fn run_network(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "dns" => {
      if values.len() != 3 {
        return Err("network dns requires 3 arguments".into());
      }
      match values[1].as_str() {
        "automatic" => restore_resolv_conf(&values[0]),
        "manual" => set_resolv_conf_manual(&values[0], &values[2]),
        _ => Err("mode must be automatic or manual".into()),
      }
    }
    _ => Err("unsupported network operation".into()),
  }
}

fn set_appearance_icons(value: &str) -> Result<(), String> {
  let enabled = match value {
    "true" => true,
    "false" => false,
    _ => return Err("config icons value must be true or false".into()),
  };
  let mut config = AppConfig::load();
  config.set_icons(enabled)
}

/// Power actions are routed to systemd-logind. Lid/Power-key behaviors are
/// applied through an ARGVUS drop-in under `/etc/systemd/logind.conf.d` (the
/// upstream config file is never overwritten) and the running logind daemon is
/// asked to re-read its configuration with a SIGHUP.
fn run_power(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "set-lid" => {
      let (context, value) = split_lid(values)?;
      let key = lid_key(context)?;
      update_logind_drop_in(&[(key, value.to_string())])?;
      reload_logind()
    }
    "set-power-button" => {
      let [value] = values else {
        return Err("power button needs one value".into());
      };
      if !POWER_KEY_VALUES.contains(&value.as_str()) {
        return Err("unsupported HandlePowerKey value".into());
      }
      update_logind_drop_in(&[("HandlePowerKey", value.to_owned())])?;
      reload_logind()
    }
    "suspend-now" => run_command("systemctl", &["suspend"]),
    "hibernate-now" => run_command("systemctl", &["hibernate"]),
    _ => Err("unsupported power operation".into()),
  }
}

fn validate_power(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "set-lid" => {
      let (_, value) = split_lid(values)?;
      if valid_lid_value(value) {
        Ok(())
      } else {
        Err(format!("unsupported HandleLidSwitch value: {value}"))
      }
    }
    "set-power-button" => {
      if values.len() != 1 || !POWER_KEY_VALUES.contains(&values[0].as_str()) {
        Err("unsupported HandlePowerKey value".into())
      } else {
        Ok(())
      }
    }
    "suspend-now" | "hibernate-now" => {
      if values.is_empty() {
        Ok(())
      } else {
        Err("suspend-now and hibernate-now take no arguments".into())
      }
    }
    _ => Err("unsupported power operation".into()),
  }
}

fn valid_lid_value(value: &str) -> bool {
  matches!(
    value,
    "ignore"
      | "poweroff"
      | "reboot"
      | "halt"
      | "kexec"
      | "suspend"
      | "hibernate"
      | "suspend-then-hibernate"
      | "lock"
      | "handled-by-system"
  )
}

const POWER_KEY_VALUES: [&str; 7] = [
  "ignore", "poweroff", "reboot", "halt", "kexec", "suspend", "lock",
];

fn split_lid(values: &[String]) -> Result<(&str, &str), String> {
  match values {
    [value] => Ok(("default", value)),
    [context, value] => {
      if !["default", "battery", "ac", "docked"].contains(&context.as_str()) {
        return Err("lid context must be default, battery, ac or docked".into());
      }
      Ok((context, value))
    }
    _ => Err("set-lid expects [value] or [context, value]".into()),
  }
}

fn lid_key(context: &str) -> Result<&'static str, String> {
  match context {
    "default" => Ok("HandleLidSwitch"),
    "battery" => Ok("HandleLidSwitch"),
    "ac" => Ok("HandleLidSwitchExternalPower"),
    "docked" => Ok("HandleLidSwitchDocked"),
    _ => Err("unsupported lid context".into()),
  }
}

const LOGIND_DROP_IN: &str = "/etc/systemd/logind.conf.d/argvus.conf";

/// Updates (or creates) the ARGVUS logind drop-in, replacing only the keys in
/// `entries` while preserving every other line and key already present.
fn update_logind_drop_in(entries: &[(&str, String)]) -> Result<(), String> {
  update_logind_drop_in_at(Path::new(LOGIND_DROP_IN), entries, true)
}

fn update_logind_drop_in_at(
  path: &Path,
  entries: &[(&str, String)],
  backup: bool,
) -> Result<(), String> {
  if fs::symlink_metadata(path)
    .map(|metadata| metadata.file_type().is_symlink())
    .unwrap_or(false)
  {
    return Err("refusing to update a symlinked logind drop-in".into());
  }
  let existing = fs::read_to_string(path).unwrap_or_default();
  let mut updated = String::new();
  let mut found: Vec<bool> = vec![false; entries.len()];
  for line in existing.lines() {
    let trimmed = line.trim_start();
    if !trimmed.starts_with('#') {
      let mut replaced = false;
      for (index, (key, _)) in entries.iter().enumerate() {
        if let Some(rest) = trimmed.strip_prefix(key)
          && rest.trim_start().starts_with('=')
        {
          updated.push_str(key);
          updated.push('=');
          updated.push_str(&entries[index].1);
          found[index] = true;
          replaced = true;
          break;
        }
      }
      if replaced {
        updated.push('\n');
        continue;
      }
      if trimmed.is_empty() && updated.ends_with('\n') {
        continue;
      }
    }
    updated.push_str(line);
    updated.push('\n');
  }
  for (index, (key, value)) in entries.iter().enumerate() {
    if !found[index] {
      if !updated.is_empty() && !updated.ends_with('\n') {
        updated.push('\n');
      }
      updated.push_str(key);
      updated.push('=');
      updated.push_str(value);
      updated.push('\n');
    }
  }
  let original = existing.trim_end();
  let written = updated.trim_end();
  if original != written {
    if backup && path.exists() {
      let _ = backup_file(path);
    }
    let metadata = fs::metadata(path)
      .or_else(|_| fs::metadata(Path::new("/etc/systemd/logind.conf")))
      .map_err(|error| error.to_string())?;
    let tmp = path.with_extension("tmp");
    {
      let mut file = fs::File::create(&tmp).map_err(|error| error.to_string())?;
      file
        .set_permissions(metadata.permissions())
        .map_err(|error| error.to_string())?;
      file
        .write_all((String::from(written) + "\n").as_bytes())
        .map_err(|error| error.to_string())?;
      file.sync_all().map_err(|error| error.to_string())?;
    }
    fs::rename(&tmp, path).map_err(|error| error.to_string())?;
  }
  Ok(())
}

fn reload_logind() -> Result<(), String> {
  let _ = run_command("systemctl", &["kill", "-s", "HUP", "systemd-logind"]);
  Ok(())
}

fn set_resolv_conf_manual(connection: &str, dns_list: &str) -> Result<(), String> {
  let servers: Vec<&str> = dns_list
    .split(',')
    .map(str::trim)
    .filter(|value| !value.is_empty())
    .collect();
  if servers.is_empty() {
    return Err("no DNS servers provided".into());
  }
  for server in &servers {
    if !valid_ipv4(server) && !valid_ipv6(server) {
      return Err(format!("invalid DNS server: {server}"));
    }
  }
  let resolv = Path::new(RESOLV_CONF);
  if fs::symlink_metadata(resolv)
    .map(|metadata| metadata.file_type().is_symlink())
    .unwrap_or(false)
  {
    return Err(
      "/etc/resolv.conf is managed by a service (symlink); use automatic DNS mode".into(),
    );
  }
  backup_resolv_conf()?;
  write_resolv_conf(&resolv_conf_contents(&servers))?;
  run_command(
    "nmcli",
    &[
      "connection",
      "modify",
      connection,
      "ipv4.dns",
      dns_list,
      "ipv6.dns",
      dns_list,
      "ipv4.ignore-auto-dns",
      "yes",
      "ipv6.ignore-auto-dns",
      "yes",
    ],
  )
}

fn restore_resolv_conf(connection: &str) -> Result<(), String> {
  let backup = Path::new(RESOLV_BACKUP);
  let restored = if backup.exists() {
    let contents = fs::read_to_string(backup).map_err(|error| error.to_string())?;
    write_resolv_conf(&contents)?;
    true
  } else {
    false
  };
  run_command(
    "nmcli",
    &[
      "connection",
      "modify",
      connection,
      "ipv4.dns",
      "",
      "ipv6.dns",
      "",
      "ipv4.ignore-auto-dns",
      "no",
      "ipv6.ignore-auto-dns",
      "no",
    ],
  )?;
  if restored {
    Ok(())
  } else {
    run_command("nmcli", &["connection", "up", connection])
  }
}

fn backup_resolv_conf() -> Result<(), String> {
  let contents = fs::read_to_string(RESOLV_CONF).map_err(|error| error.to_string())?;
  if contents.contains(RESOLV_MARKER) || Path::new(RESOLV_BACKUP).exists() {
    return Ok(());
  }
  let mut file = fs::OpenOptions::new()
    .write(true)
    .create_new(true)
    .open(RESOLV_BACKUP)
    .map_err(|error| error.to_string())?;
  file
    .write_all(contents.as_bytes())
    .map_err(|error| error.to_string())?;
  file.sync_all().map_err(|error| error.to_string())
}

fn write_resolv_conf(contents: &str) -> Result<(), String> {
  let path = Path::new(RESOLV_CONF);
  let tmp = path.with_extension("argvus-control-center.tmp");
  {
    let mut file = fs::File::create(&tmp).map_err(|error| error.to_string())?;
    file
      .set_permissions(fs::Permissions::from_mode(0o644))
      .map_err(|error| error.to_string())?;
    file
      .write_all(contents.as_bytes())
      .map_err(|error| error.to_string())?;
    file.sync_all().map_err(|error| error.to_string())?;
  }
  fs::rename(&tmp, path).map_err(|error| error.to_string())
}

fn resolv_conf_contents(servers: &[&str]) -> String {
  let bodies = servers
    .iter()
    .map(|server| format!("nameserver {server}"))
    .collect::<Vec<_>>()
    .join("\n");
  format!("{RESOLV_MARKER}\n{bodies}\n")
}

fn valid_ipv4(value: &str) -> bool {
  !value.is_empty() && value.parse::<Ipv4Addr>().is_ok()
}

fn valid_ipv6(value: &str) -> bool {
  !value.is_empty() && value.parse::<Ipv6Addr>().is_ok()
}

fn validate_args(args: &[String]) -> Result<(), String> {
  match args {
    [area, action, value] if area == "timezone" && action == "set" => {
      if time::is_valid_timezone_name(value) {
        Ok(())
      } else {
        Err(format!("invalid time zone: {value}"))
      }
    }
    [area, action, value] if area == "hostname" && action == "set" => {
      host::validate_hostname(value)
    }
    [area, action, value] if area == "datetime" && action == "ntp" => match value.as_str() {
      "true" | "false" => Ok(()),
      _ => Err("NTP value must be true or false".to_string()),
    },
    [area, action, value] if area == "datetime" && action == "set" => {
      time::is_valid_datetime(value)
        .then_some(())
        .ok_or_else(|| "invalid date/time (expected YYYY-MM-DD HH:MM:SS)".to_string())
    }
    [area, action, value] if area == "locale" && action == "set-lang" => {
      if locale::is_locale_name(value) {
        Ok(())
      } else {
        Err(format!("invalid locale: {value}"))
      }
    }
    [area, action, values @ ..] if area == "locale" && action == "set-generated" => {
      for value in values {
        let Some((name, encoding)) = value.split_once(' ') else {
          return Err(format!("invalid locale.gen entry: {value}"));
        };
        if !locale::is_locale_name(name) || !locale::is_encoding_name(encoding) {
          return Err(format!("invalid locale.gen entry: {value}"));
        }
      }
      Ok(())
    }
    [area, action, layout] if area == "keyboard" && action == "layout" => {
      if keyboard::is_xkb_name(layout) {
        Ok(())
      } else {
        Err(format!("invalid keyboard layout: {layout}"))
      }
    }
    [area, action, layout, variant] if area == "keyboard" && action == "variant" => {
      if keyboard::is_xkb_name(layout) && (variant.is_empty() || keyboard::is_xkb_name(variant)) {
        Ok(())
      } else {
        Err("invalid keyboard variant".to_string())
      }
    }
    [area, action, keymap] if area == "keyboard" && action == "console-keymap" => {
      if keyboard::is_keymap_name(keymap) {
        Ok(())
      } else {
        Err(format!("invalid console keymap: {keymap}"))
      }
    }
    [area, action, unit] if area == "service" => service_args(action, unit).map(|_| ()),
    [area, action, governor] if area == "governor" && action == "set" => (!governor.is_empty()
      && governor.len() <= 64
      && governor
        .chars()
        .all(|value| value.is_ascii_alphanumeric() || matches!(value, '-' | '_')))
    .then_some(())
    .ok_or_else(|| "unsupported governor".into()),
    [area, action, values @ ..] if area == "power" => validate_power(action, values),
    [area, action, values @ ..] if area == "boot" => validate_boot(action, values),
    [area, action, values @ ..] if area == "package" => validate_package(action, values),
    [area, action, values @ ..] if area == "network" => validate_network(action, values),
    [area, action, value] if area == "config" && action == "icons" => match value.as_str() {
      "true" | "false" => Ok(()),
      _ => Err("config icons value must be true or false".to_string()),
    },
    _ => {
      Err("usage: argvus-control-center system-settings <domain> <action> [value...]".to_string())
    }
  }
}

fn validate_network(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "dns" => {
      if values.len() != 3 {
        return Err("network dns requires 3 arguments".into());
      }
      if values[0].is_empty() || values[0].contains('\n') || values[0].contains('\'') {
        return Err("invalid connection name/uuid".into());
      }
      if values[1] != "automatic" && values[1] != "manual" {
        return Err("mode must be automatic or manual".into());
      }
      if values[1] == "manual" {
        for server in values[2]
          .split(',')
          .map(str::trim)
          .filter(|value| !value.is_empty())
        {
          if !valid_ipv4(server) && !valid_ipv6(server) {
            return Err(format!("invalid DNS server: {server}"));
          }
        }
      }
      Ok(())
    }
    _ => Err("unsupported network operation".into()),
  }
}

fn valid_package_name(value: &str) -> bool {
  !value.is_empty()
    && value.len() <= 128
    && value
      .chars()
      .all(|c| c.is_ascii_alphanumeric() || matches!(c, '@' | '.' | '_' | '+' | '-'))
}

fn validate_package(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "upgrade" if values.is_empty() => Ok(()),
    "upgrade-package" if values.len() == 1 && valid_package_name(&values[0]) => Ok(()),
    "refresh-db" if values.is_empty() => Ok(()),
    "install" | "remove" | "reinstall" => {
      if values.is_empty() || values.iter().any(|value| !valid_package_name(value)) {
        return Err("invalid package name".into());
      }
      Ok(())
    }
    "downgrade" => {
      if values.len() != 1
        || !values[0].starts_with("/var/cache/pacman/pkg/")
        || values[0].contains("..")
      {
        return Err("invalid cached package path".into());
      }
      let path = Path::new(&values[0]);
      (path.is_file()
        && !path.is_symlink()
        && path
          .extension()
          .is_some_and(|e| e == "zst" || e == "xz" || e == "gz"))
      .then_some(())
      .ok_or_else(|| "cached package was not found".into())
    }
    "clean-cache"
      if values.len() == 1
        && matches!(
          values[0].as_str(),
          "keep-three" | "keep-one" | "uninstalled"
        ) =>
    {
      Ok(())
    }
    "mirror-apply" if values.len() == 1 => {
      let content = &values[0];
      (!content.is_empty()
        && content.len() <= 256 * 1024
        && content
          .lines()
          .any(|line| line.trim_start().starts_with("Server = "))
        && content
          .chars()
          .all(|c| !c.is_control() || c == '\n' || c == '\t'))
      .then_some(())
      .ok_or_else(|| "invalid mirrorlist".into())
    }
    _ => Err("unsupported package operation".into()),
  }
}

fn run_package(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "install" => stream_pacman(&["-S", "--needed"], values),
    "remove" => stream_pacman(&["-Rns"], values),
    "reinstall" => stream_pacman(&["-S"], values),
    "upgrade" => stream_pacman(&["-Syu"], &[]),
    "upgrade-package" => stream_pacman(&["-S"], values),
    "refresh-db" => stream_pacman(&["-Syy"], &[]),
    "downgrade" => stream_pacman(&["-U"], values),
    "clean-cache" => stream_command(
      "paccache",
      &[
        "-r",
        match values[0].as_str() {
          "keep-three" => "-k3",
          "keep-one" => "-k1",
          _ => "-u",
        },
      ],
    ),
    "mirror-apply" => {
      update_mirrorlist(&values[0])?;
      println!("ok");
      Ok(())
    }
    _ => Err("unsupported package operation".into()),
  }
}

fn stream_pacman(prefix: &[&str], values: &[String]) -> Result<(), String> {
  let mut args: Vec<&str> = prefix.to_vec();
  args.push("--noconfirm");
  args.extend(values.iter().map(String::as_str));
  stream_command("pacman", &args)
}

fn update_mirrorlist(content: &str) -> Result<(), String> {
  let path = Path::new("/etc/pacman.d/mirrorlist");
  if path.is_symlink() {
    return Err("refusing to update a symlinked mirrorlist".into());
  }
  backup_file(path)?;
  boot_write_atomic(path, content)
}

fn service_args(action: &str, unit: &str) -> Result<Vec<String>, String> {
  if !unit.ends_with(".service")
    || unit.is_empty()
    || unit.len() > 255
    || unit
      .chars()
      .any(|value| value.is_control() || value.is_whitespace())
  {
    return Err("invalid systemd unit".into());
  }
  let args = match action {
    "start" | "stop" | "restart" | "enable" | "disable" => vec![action.into(), unit.into()],
    "enable-now" => vec!["enable".into(), "--now".into(), unit.into()],
    "disable-now" => vec!["disable".into(), "--now".into(), unit.into()],
    _ => return Err("unsupported service action".into()),
  };
  Ok(args)
}

fn set_governor(value: &str) -> Result<(), String> {
  if locate_command(&["powerprofilesctl"]).is_some() {
    let profile = match value {
      "performance" => Some("performance"),
      "powersave" | "power-saver" => Some("power-saver"),
      "balanced" => Some("balanced"),
      _ => None,
    };
    if let Some(profile) = profile
      && run_command("powerprofilesctl", &["set", profile]).is_ok()
    {
      return Ok(());
    }
  }
  let mut changed = 0;
  if let Ok(entries) = fs::read_dir("/sys/devices/system/cpu/cpufreq") {
    for entry in entries.flatten() {
      let path = entry.path();
      let available =
        fs::read_to_string(path.join("scaling_available_governors")).unwrap_or_default();
      if available
        .split_whitespace()
        .any(|candidate| candidate == value)
        && fs::write(path.join("scaling_governor"), format!("{value}\n")).is_ok()
      {
        changed += 1;
      }
    }
  }
  if let Ok(entries) = fs::read_dir("/sys/devices/system/cpu") {
    for entry in entries.flatten() {
      if !entry.file_name().to_string_lossy().starts_with("cpu") {
        continue;
      }
      let path = entry.path().join("cpufreq");
      let available =
        fs::read_to_string(path.join("scaling_available_governors")).unwrap_or_default();
      if available
        .split_whitespace()
        .any(|candidate| candidate == value)
        && fs::write(path.join("scaling_governor"), format!("{value}\n")).is_ok()
      {
        changed += 1;
      }
    }
  }
  (changed > 0)
    .then_some(())
    .ok_or_else(|| "no compatible cpufreq policy found".into())
}

fn validate_boot(action: &str, values: &[String]) -> Result<(), String> {
  let token = |value: &str| {
    !value.is_empty()
      && value.len() <= 255
      && value
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || matches!(character, '.' | '_' | '-'))
  };
  match action {
    "systemd-default" if values.len() == 1 => token(&values[0])
      .then_some(())
      .ok_or_else(|| "invalid systemd-boot entry".into()),
    "systemd-timeout" | "grub-timeout" if values.len() == 1 => values[0]
      .parse::<u32>()
      .ok()
      .filter(|value| *value <= 60)
      .map(|_| ())
      .ok_or_else(|| "timeout must be between 0 and 60".into()),
    "grub-cmdline" if values.len() == 1 => (!values[0].is_empty()
      && values[0].len() <= 2048
      && values[0]
        .chars()
        .all(|character| !character.is_control() && !matches!(character, '"' | '\\')))
    .then_some(())
    .ok_or_else(|| "invalid GRUB kernel command line".into()),
    "grub-regenerate" | "initramfs-regenerate" if values.is_empty() => Ok(()),
    "plymouth-theme" if values.len() == 1 => token(&values[0])
      .then_some(())
      .ok_or_else(|| "invalid Plymouth theme".into()),
    _ => Err("unsupported boot operation".into()),
  }
}

fn run_boot(action: &str, values: &[String]) -> Result<(), String> {
  match action {
    "systemd-default" => {
      let root = boot_root().ok_or("systemd-boot ESP was not found")?;
      let direct = root.join("loader/entries").join(&values[0]);
      let named = root
        .join("loader/entries")
        .join(format!("{}.conf", values[0]));
      if (!direct.is_file() || direct.is_symlink()) && (!named.is_file() || named.is_symlink()) {
        return Err("systemd-boot entry was not found".into());
      }
      stream_command(
        "bootctl",
        &[
          &format!("--esp-path={}", root.display()),
          "set-default",
          &values[0],
        ],
      )
    }
    "systemd-timeout" => {
      let root = boot_root().ok_or("systemd-boot ESP was not found")?;
      update_boot_key(&root.join("loader/loader.conf"), "timeout", &values[0])?;
      println!("ok");
      Ok(())
    }
    "grub-timeout" => {
      update_boot_key(Path::new("/etc/default/grub"), "GRUB_TIMEOUT", &values[0])?;
      println!("ok");
      Ok(())
    }
    "grub-cmdline" => {
      update_boot_key(
        Path::new("/etc/default/grub"),
        "GRUB_CMDLINE_LINUX_DEFAULT",
        &values[0],
      )?;
      println!("ok");
      Ok(())
    }
    "grub-regenerate" => {
      let config = ["/boot/grub/grub.cfg", "/boot/grub2/grub.cfg"]
        .iter()
        .map(Path::new)
        .find(|path| path.is_file())
        .ok_or("GRUB configuration path was not found")?;
      let tool = locate_command(&["grub-mkconfig", "grub2-mkconfig"])
        .ok_or("grub-mkconfig was not found")?;
      let config = config.to_string_lossy().into_owned();
      stream_command_path(&tool, &["-o", &config])
    }
    "initramfs-regenerate" => stream_command("mkinitcpio", &["-P"]),
    "plymouth-theme" => {
      let path = Path::new("/usr/share/plymouth/themes").join(&values[0]);
      if !path.is_dir() || path.is_symlink() {
        return Err("Plymouth theme was not found".into());
      }
      stream_command("plymouth-set-default-theme", &["-R", values[0].as_str()])
    }
    _ => Err("unsupported boot operation".into()),
  }
}

fn boot_root() -> Option<PathBuf> {
  ["/boot", "/efi", "/boot/efi"]
    .iter()
    .map(PathBuf::from)
    .find(|root| root.join("loader/loader.conf").is_file() || root.join("loader/entries").is_dir())
}

fn update_boot_key(path: &Path, key: &str, value: &str) -> Result<(), String> {
  if path.is_symlink() {
    return Err("refusing to update a symlinked boot configuration".into());
  }
  let contents = fs::read_to_string(path).map_err(|error| error.to_string())?;
  let mut found = false;
  let mut updated = String::new();
  for line in contents.lines() {
    let trimmed = line.trim_start();
    if !trimmed.starts_with('#') && trimmed.split_whitespace().next() == Some(key) {
      updated.push_str(key);
      updated.push(' ');
      updated.push_str(value);
      found = true;
    } else if key.starts_with("GRUB_")
      && !trimmed.starts_with('#')
      && trimmed.starts_with(&format!("{key}="))
    {
      updated.push_str(key);
      updated.push_str("=\"");
      updated.push_str(value);
      updated.push('"');
      found = true;
    } else {
      updated.push_str(line);
    }
    updated.push('\n');
  }
  if !found {
    if key.starts_with("GRUB_") {
      updated.push_str(&format!("{key}=\"{value}\"\n"));
    } else {
      updated.push_str(&format!("{key} {value}\n"));
    }
  }
  if updated != contents {
    backup_file(path)?;
    boot_write_atomic(path, &updated)?;
  }
  Ok(())
}

fn backup_file(path: &Path) -> Result<PathBuf, String> {
  let stamp = SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .unwrap_or_default()
    .as_secs();
  for suffix in 0..1000 {
    let backup = PathBuf::from(format!("{}.argvus-backup-{stamp}-{suffix}", path.display()));
    match fs::OpenOptions::new()
      .write(true)
      .create_new(true)
      .open(&backup)
    {
      Ok(mut file) => {
        file
          .write_all(&fs::read(path).map_err(|error| error.to_string())?)
          .map_err(|error| error.to_string())?;
        file.sync_all().map_err(|error| error.to_string())?;
        return Ok(backup);
      }
      Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
      Err(error) => return Err(error.to_string()),
    }
  }
  Err("could not create a unique boot backup".into())
}

fn boot_write_atomic(path: &Path, contents: &str) -> Result<(), String> {
  let metadata = fs::metadata(path).map_err(|error| error.to_string())?;
  let tmp = path.with_extension(format!("argvus-control-center-{}.tmp", std::process::id()));
  let mut file = fs::File::create(&tmp).map_err(|error| error.to_string())?;
  file
    .set_permissions(metadata.permissions())
    .map_err(|error| error.to_string())?;
  file
    .write_all(contents.as_bytes())
    .map_err(|error| error.to_string())?;
  file.sync_all().map_err(|error| error.to_string())?;
  fs::rename(&tmp, path).map_err(|error| error.to_string())
}

fn locate_command(names: &[&str]) -> Option<PathBuf> {
  std::env::var_os("PATH").and_then(|path| {
    std::env::split_paths(&path)
      .flat_map(|dir| names.iter().map(move |name| dir.join(name)))
      .find(|candidate| candidate.is_file())
  })
}

fn stream_command(command: &str, args: &[&str]) -> Result<(), String> {
  stream_command_display(command, Path::new(command), args)
}

fn stream_command_path(command: &Path, args: &[&str]) -> Result<(), String> {
  stream_command_display(&command.display().to_string(), command, args)
}

fn stream_command_display(display: &str, command: &Path, args: &[&str]) -> Result<(), String> {
  let mut child = Command::new(command)
    .args(args)
    .stdin(Stdio::null())
    .stdout(Stdio::piped())
    .stderr(Stdio::piped())
    .spawn()
    .map_err(|error| format!("{display}: {error}"))?;
  let stdout = child
    .stdout
    .take()
    .ok_or_else(|| format!("{display}: stdout was not captured"))?;
  let stderr = child
    .stderr
    .take()
    .ok_or_else(|| format!("{display}: stderr was not captured"))?;
  let stdout_forwarder = std::thread::spawn(move || forward_lines(BufReader::new(stdout)));
  let stderr_forwarder = std::thread::spawn(move || forward_lines(BufReader::new(stderr)));
  let status = child
    .wait()
    .map_err(|error| format!("{display}: {error}"))?;
  let stdout_lines = stdout_forwarder.join().unwrap_or_default();
  let stderr_lines = stderr_forwarder.join().unwrap_or_default();
  let any_output = !stdout_lines.is_empty() || !stderr_lines.is_empty();
  if status.success() {
    if !any_output {
      println!("ok");
    }
    Ok(())
  } else {
    let stderr = stderr_lines.concat().trim().to_string();
    Err(if stderr.is_empty() {
      format!("{display} exited with {status}")
    } else {
      stderr
    })
  }
}

fn forward_lines(mut pipe: impl BufRead) -> Vec<String> {
  let mut lines = Vec::new();
  let mut line = String::new();
  loop {
    line.clear();
    match pipe.read_line(&mut line) {
      Ok(0) => break,
      Ok(_) => {
        let stdout = std::io::stdout();
        let mut handle = stdout.lock();
        let _ = handle.write_all(line.as_bytes());
        let _ = handle.flush();
        lines.push(std::mem::take(&mut line));
      }
      Err(_) => break,
    }
  }
  lines
}

fn ensure_root(args: &[String]) -> Result<(), String> {
  if effective_uid() == 0 || std::env::var_os(ELEVATED_ENV).is_some() {
    return Ok(());
  }
  let pkexec = locate_pkexec().ok_or_else(|| "pkexec was not found; install polkit".to_string())?;
  let exe = std::env::current_exe().map_err(|error| error.to_string())?;
  let mut command = Command::new(pkexec);
  command
    .arg(exe)
    .arg("system-settings")
    .args(args)
    .env_clear()
    .env(ELEVATED_ENV, "1");
  if let Some(value) = std::env::var_os("PATH") {
    command.env("PATH", value);
  } else {
    command.env(
      "PATH",
      "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin",
    );
  }
  if let Some(value) = std::env::var_os("DBUS_SESSION_BUS_ADDRESS") {
    command.env("DBUS_SESSION_BUS_ADDRESS", value);
  }
  if let Some(value) = std::env::var_os("DBUS_SYSTEM_BUS_ADDRESS") {
    command.env("DBUS_SYSTEM_BUS_ADDRESS", value);
  }
  if let Some(value) = std::env::var_os("XDG_RUNTIME_DIR") {
    command.env("XDG_RUNTIME_DIR", value);
  }
  let error = command.exec();
  Err(format!("failed to launch pkexec: {error}"))
}

fn effective_uid() -> u32 {
  fs::read_to_string("/proc/self/status")
    .ok()
    .and_then(|contents| {
      contents.lines().find_map(|line| {
        line
          .strip_prefix("Uid:")
          .and_then(|rest| rest.split_whitespace().nth(1))
          .and_then(|value| value.parse().ok())
      })
    })
    .unwrap_or(1)
}

fn locate_pkexec() -> Option<PathBuf> {
  std::env::var_os("PATH").and_then(|path| {
    std::env::split_paths(&path)
      .map(|dir| dir.join("pkexec"))
      .find(|candidate| candidate.is_file())
  })
}

fn set_generated_locales(values: &[String]) -> Result<(), String> {
  let path = Path::new(LOCALE_GEN);
  let contents = fs::read_to_string(path).map_err(|error| format!("{LOCALE_GEN}: {error}"))?;
  let entries = locale::parse_locale_gen(&contents);
  let valid: BTreeSet<String> = entries
    .iter()
    .map(|entry| format!("{} {}", entry.locale, entry.encoding))
    .collect();
  let selected: BTreeSet<String> = values.iter().cloned().collect();
  for value in &selected {
    if !valid.contains(value) {
      return Err(format!("locale is not listed in {LOCALE_GEN}: {value}"));
    }
  }
  let updated = locale::apply_locale_gen(&contents, &selected);
  if updated != contents {
    write_atomic(path, &updated)?;
  }
  stream_command("locale-gen", &[])
}

fn write_atomic(path: &Path, contents: &str) -> Result<(), String> {
  let metadata = fs::metadata(path).map_err(|error| error.to_string())?;
  let tmp = path.with_extension("argvus-control-center.tmp");
  {
    let mut file = fs::File::create(&tmp).map_err(|error| error.to_string())?;
    file
      .set_permissions(fs::Permissions::from_mode(metadata.permissions().mode()))
      .map_err(|error| error.to_string())?;
    file
      .write_all(contents.as_bytes())
      .map_err(|error| error.to_string())?;
    file.sync_all().map_err(|error| error.to_string())?;
  }
  fs::rename(&tmp, path).map_err(|error| error.to_string())
}

fn run_command(command: &str, args: &[&str]) -> Result<(), String> {
  let output = Command::new(command)
    .args(args)
    .stdin(Stdio::null())
    .output()
    .map_err(|error| format!("{command}: {error}"))?;
  if output.status.success() {
    let stdout = String::from_utf8_lossy(&output.stdout);
    if stdout.trim().is_empty() {
      println!("ok");
    } else {
      print!("{stdout}");
    }
    Ok(())
  } else {
    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
    Err(if stderr.is_empty() {
      format!("{command} exited with {}", output.status)
    } else {
      stderr
    })
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::sync::Mutex;
  use std::sync::atomic::AtomicUsize;

  static CONFIG_TEST_LOCK: Mutex<()> = Mutex::new(());
  static CONFIG_TEST_SEQUENCE: AtomicUsize = AtomicUsize::new(0);

  #[test]
  fn rejects_injection_like_arguments() {
    assert!(validate_args(&["timezone".into(), "set".into(), "UTC;reboot".into()]).is_err());
    assert!(validate_args(&["hostname".into(), "set".into(), "bad name".into()]).is_err());
    assert!(validate_args(&["keyboard".into(), "layout".into(), "br".into()]).is_ok());
  }

  #[test]
  fn validates_boot_operations_without_accepting_paths_or_bad_timeouts() {
    assert!(validate_boot("systemd-default", &["arch.conf".into()]).is_ok());
    assert!(validate_boot("systemd-default", &["../evil".into()]).is_err());
    assert!(validate_boot("systemd-timeout", &["60".into()]).is_ok());
    assert!(validate_boot("systemd-timeout", &["61".into()]).is_err());
    assert!(validate_boot("grub-cmdline", &["quiet splash".into()]).is_ok());
    assert!(validate_boot("grub-cmdline", &["bad\nline".into()]).is_err());
    assert!(validate_boot("plymouth-theme", &["argvus-splash".into()]).is_ok());
    assert!(validate_boot("plymouth-theme", &["theme/name".into()]).is_err());
  }

  #[test]
  fn validates_package_operations_without_partial_upgrade_or_arbitrary_paths() {
    assert!(validate_package("install", &["firefox".into()]).is_ok());
    assert!(validate_package("upgrade", &[]).is_ok());
    assert!(validate_package("install", &["foo;reboot".into()]).is_err());
    assert!(validate_package("downgrade", &["/tmp/package.pkg.tar.zst".into()]).is_err());
    assert!(validate_package("clean-cache", &["keep-three".into()]).is_ok());
    assert!(validate_package("clean-cache", &["all".into()]).is_err());
    assert!(
      validate_package(
        "mirror-apply",
        &["Server = https://mirror.example/$repo/os/$arch\n".into()]
      )
      .is_ok()
    );
  }

  #[test]
  fn validates_individual_install_and_reinstall_operations() {
    assert!(validate_package("install", &["firefox".into()]).is_ok());
    assert!(validate_package("reinstall", &["firefox".into()]).is_ok());
  }

  #[test]
  fn validates_network_dns_modes_and_servers() {
    assert!(validate_network("dns", &["eth0".into(), "automatic".into(), "".into()]).is_ok());
    assert!(
      validate_network(
        "dns",
        &["eth0".into(), "manual".into(), "1.1.1.1,8.8.8.8".into()]
      )
      .is_ok()
    );
    assert!(
      validate_network(
        "dns",
        &[
          "eth0".into(),
          "manual".into(),
          "2001:4860:4860::8888".into()
        ]
      )
      .is_ok()
    );
    assert!(
      validate_network(
        "dns",
        &[
          "eth0".into(),
          "manual".into(),
          "1.1.1.1,not-a-server".into()
        ]
      )
      .is_err()
    );
    assert!(validate_network("dns", &["".into(), "manual".into(), "1.1.1.1".into()],).is_err());
    assert!(
      validate_network("dns", &["eth'0".into(), "manual".into(), "1.1.1.1".into()],).is_err()
    );
  }

  #[test]
  fn validates_icons_only_accepts_booleans() {
    assert!(validate_args(&["config".into(), "icons".into(), "true".into()]).is_ok());
    assert!(validate_args(&["config".into(), "icons".into(), "false".into()]).is_ok());
    assert!(validate_args(&["config".into(), "icons".into(), "yes".into()]).is_err());
    assert!(validate_args(&["config".into(), "other".into(), "true".into()]).is_err());
  }

  #[test]
  fn validates_power_lid_and_button_values() {
    assert!(validate_power("set-lid", &["suspend".into()]).is_ok());
    assert!(validate_power("set-lid", &["battery".into(), "hibernate".into()]).is_ok());
    assert!(validate_power("set-lid", &["ac".into(), "poweroff".into()]).is_ok());
    assert!(validate_power("set-lid", &["docked".into(), "lock".into()]).is_ok());
    assert!(validate_power("set-lid", &["ac".into(), "explode".into()]).is_err());
    assert!(validate_power("set-lid", &["wrong-context".into(), "suspend".into()]).is_err());
    assert!(validate_power("set-power-button", &["poweroff".into()]).is_ok());
    assert!(validate_power("set-power-button", &["suspend".into()]).is_ok());
    assert!(validate_power("set-power-button", &["hibernate".into()]).is_err());
    assert!(validate_power("set-power-button", &[]).is_err());
    assert!(validate_power("unsupported", &[]).is_err());
  }

  #[test]
  fn power_lid_contexts_map_to_logind_keys() {
    assert_eq!(lid_key("default").unwrap(), "HandleLidSwitch");
    assert_eq!(lid_key("battery").unwrap(), "HandleLidSwitch");
    assert_eq!(lid_key("ac").unwrap(), "HandleLidSwitchExternalPower");
    assert_eq!(lid_key("docked").unwrap(), "HandleLidSwitchDocked");
    assert!(lid_key("sleepy").is_err());
  }

  #[test]
  fn logind_drop_in_preserves_existing_keys() {
    let dir = temp_dir().join(format!("argvus-logind-drop-in-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("argvus.conf");
    std::fs::write(
      &path,
      "HandleLidSwitch=suspend\n# a comment\nHandlePowerKey=poweroff\n",
    )
    .unwrap();
    let entries: [(&str, String); 1] = [("HandleLidSwitch", "lock".into())];
    assert_eq!(
      update_logind_drop_in_at(&path, &entries, true),
      Ok(()),
      "drop-in is written once"
    );
    let contents = std::fs::read_to_string(&path).unwrap();
    assert!(contents.contains("HandleLidSwitch=lock"), "{contents}");
    assert!(contents.contains("HandlePowerKey=poweroff"), "{contents}");
    assert!(contents.contains("# a comment"), "{contents}");
    let _ = std::fs::remove_dir_all(&dir);
  }

  #[test]
  fn logind_drop_in_creates_missing_file() {
    let dir = temp_dir().join(format!("argvus-logind-drop-in-new-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("argvus.conf");
    let entries: [(&str, String); 2] = [
      ("HandleLidSwitch", "suspend-then-hibernate".into()),
      ("HandlePowerKey", "lock".into()),
    ];
    assert_eq!(update_logind_drop_in_at(&path, &entries, true), Ok(()));
    let contents = std::fs::read_to_string(&path).unwrap();
    assert!(
      contents.contains("HandleLidSwitch=suspend-then-hibernate"),
      "{contents}"
    );
    assert!(contents.contains("HandlePowerKey=lock"), "{contents}");
    let _ = std::fs::remove_dir_all(&dir);
  }

  fn temp_dir() -> PathBuf {
    std::env::var_os("TMPDIR")
      .map(PathBuf::from)
      .unwrap_or_else(|| PathBuf::from("/tmp"))
  }

  #[test]
  fn validates_and_applies_appearance_icons() {
    let _guard = CONFIG_TEST_LOCK.lock().unwrap();
    let sequence = CONFIG_TEST_SEQUENCE.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!(
      "argvus-cc-command-config-{}-{sequence}",
      std::process::id()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("config.toml");
    std::fs::write(&path, "[Appearance]\nicons = true\n").unwrap();
    unsafe {
      std::env::set_var("ARGVUS_CONFIG_PATH", &path);
    }
    assert!(set_appearance_icons("maybe").is_err());
    assert!(set_appearance_icons("nope").is_err());
    set_appearance_icons("false").unwrap();
    assert!(!AppConfig::icons_enabled());
    let contents = std::fs::read_to_string(&path).unwrap();
    assert!(contents.contains("icons = false"), "{contents}");
    set_appearance_icons("true").unwrap();
    assert!(AppConfig::icons_enabled());
    unsafe {
      std::env::remove_var("ARGVUS_CONFIG_PATH");
    }
    let _ = std::fs::remove_dir_all(&dir);
  }

  #[test]
  fn resolv_conf_content_marks_manual_servers() {
    assert_eq!(
      resolv_conf_contents(&["1.1.1.1", "8.8.8.8"]),
      format!("{RESOLV_MARKER}\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n")
    );
    assert!(valid_ipv4("192.168.0.1"));
    assert!(!valid_ipv4("999.1.1.1"));
    assert!(valid_ipv6("2001:db8::1"));
    assert!(!valid_ipv6("not-an-ip"));
  }
}
