[package]
name = "argvus-control-center-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
argvus-i18n = { path = "../argvus-i18n" }
argvus-theme = { path = "../argvus-theme" }
argvus-tui = { path = "../argvus-tui" }
argvus-control-center-apps = { path = "../argvus-control-center-apps" }
argvus-control-center-core = { path = "../argvus-control-center-core" }
crossterm.workspace = true
ratatui.workspace = true
thiserror.workspace = true

[[bin]]
name = "argvus-system-settings"
path = "src/bin/argvus-system-settings.rs"
