[package]
name = "argvus-control-center-bluetooth"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
argvus-control-center-core = { path = "../argvus-control-center-core" }
argvus-i18n = { path = "../argvus-i18n" }
argvus-theme = { path = "../argvus-theme" }
argvus-tui = { path = "../argvus-tui" }
crossterm.workspace = true
ratatui.workspace = true
thiserror.workspace = true
zbus.workspace = true
