//! Implements Hypridle configuration generation in crate `argvus control center power`. This separation keeps external effects from contaminating models, routes, or rendering.
//!
//! External tool dependencies remain in backend layers;
//! the UI consumes normalized models and results.
use argvus_control_center_core::paths::argvus_config_home;
use std::fs;
use std::path::PathBuf;
use std::sync::{Mutex, OnceLock, mpsc};
use std::time::Duration;

/// The ARGVUS hypridle configuration lives under the user config path.
/// This matches the path resolved by `paths_config power/config/hypridle.conf` when
/// ARGVUS_MUTABLE_CONFIG=1 (used by argvus-session and argvus-power scripts).
pub fn config_path() -> PathBuf {
  argvus_config_home().join("hypr/hypridle.conf")
}

/// Defines the constant `DEFAULT_HYPRIDLE_CONF`. Its explicit shape preserves the contract consumed by the rest of the workspace and keeps the intent visible as the module evolves.
const DEFAULT_HYPRIDLE_CONF: &str = r#"# ARGVUS hypridle configuration
# Generated by ARGVUS Control Center

general {
  lock_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
  before_sleep_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}
"#;

/// Returns the screen-off idle timeout in whole minutes.
pub fn screen_off_minutes() -> Option<u32> {
  let content = fs::read_to_string(config_path()).ok()?;
  listener_minutes_from(&content, calls_dpms_off)
}

/// Returns the screen-lock idle timeout in whole minutes.
pub fn lock_minutes() -> Option<u32> {
  let content = fs::read_to_string(config_path()).ok()?;
  listener_minutes_from(&content, calls_lock)
}

/// Updates the timeout of the listener whose `on-timeout` matches `matches`
/// and returns the new full configuration text. Errors when no such listener
/// exists, so we never guess at foreign layouts.
fn set_listener_minutes(
  content: &str,
  minutes: u32,
  matches: fn(&str) -> bool,
) -> Result<String, String> {
  let target = find_listener_timeout(content, matches).ok_or_else(|| {
    "O hypridle do ARGVUS não define um listener correspondente; nada foi alterado.".to_string()
  })?;
  let new_seconds = minutes.saturating_mul(60);
  let mut updated = String::with_capacity(content.len());
  for (index, line) in content.lines().enumerate() {
    if index == target {
      let indent: String = line
        .chars()
        .take_while(|character| character.is_whitespace())
        .collect();
      updated.push_str(&format!("{indent}timeout = {new_seconds}\n"));
    } else {
      updated.push_str(line);
      updated.push('\n');
    }
  }
  Ok(updated)
}

/// Updates the timeout of the DPMS-off listener and returns the new config text.
pub fn set_screen_off_minutes(content: &str, minutes: u32) -> Result<String, String> {
  set_listener_minutes(content, minutes, calls_dpms_off)
}

/// Updates the timeout of the screen-lock listener and returns the new config text.
pub fn set_lock_minutes(content: &str, minutes: u32) -> Result<String, String> {
  set_listener_minutes(content, minutes, calls_lock)
}

/// Builds a config by appending an active DPMS-off listener. Used when the
/// existing config has no recognizable screen-off listener (the stock ARGVUS
/// config ships with that example commented out), preserving everything else
/// such as the inactivity-lock listener.
fn with_screen_off_listener(content: &str, minutes: u32) -> String {
  let seconds = minutes.saturating_mul(60);
  let base = content.trim_end_matches(['\r', '\n']).to_string();
  format!(
    "{base}\n\nlistener {{\n  timeout = {seconds}\n  on-timeout = hyprctl dispatch 'hl.dsp.dpms({{ action = \"off\" }})'\n  on-resume = hyprctl dispatch 'hl.dsp.dpms({{ action = \"on\" }})'\n}}\n"
  )
}

/// Builds a config by appending an active screen-lock listener, reusing the
/// configured `general.lock_cmd` so a custom lock command survives the
/// "never" → value round trip.
fn with_lock_listener(content: &str, minutes: u32) -> String {
  let seconds = minutes.saturating_mul(60);
  let command = lock_command(content);
  let base = content.trim_end_matches(['\r', '\n']).to_string();
  format!("{base}\n\nlistener {{\n  timeout = {seconds}\n  on-timeout = {command}\n}}\n")
}

/// Removes the listener block whose `on-timeout` matches, disabling the related
/// auto action (the "never" option) while preserving every other listener.
fn remove_listener(content: &str, matches: fn(&str) -> bool) -> String {
  let pieces: Vec<&str> = content.split_inclusive('\n').collect();
  let mut drop = vec![false; pieces.len()];
  let mut in_listener = false;
  let mut matched = false;
  let mut start = 0;
  for (index, piece) in pieces.iter().enumerate() {
    let trimmed = piece.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') {
      continue;
    }
    if !in_listener && trimmed.starts_with("listener") && trimmed.ends_with('{') {
      in_listener = true;
      matched = false;
      start = index;
      continue;
    }
    if in_listener {
      if trimmed.starts_with("on-timeout") && matches(trimmed) {
        matched = true;
      }
      if trimmed.ends_with('}') {
        if matched {
          for line in &mut drop[start..=index] {
            *line = true;
          }
        }
        in_listener = false;
      }
    }
  }
  pieces
    .into_iter()
    .zip(drop)
    .filter_map(|(piece, remove)| (!remove).then_some(piece))
    .collect()
}

/// Shared apply: persists a listener timeout (or disables it with `0`) and
/// requests a hypridle restart. Returns the previous value in minutes.
fn apply_listener_minutes(
  minutes: u32,
  matches: fn(&str) -> bool,
  setter: fn(&str, u32) -> Result<String, String>,
  listener_template: fn(&str, u32) -> String,
) -> Result<u32, String> {
  let path = config_path();

  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent).map_err(|error| error.to_string())?;
  }

  if fs::symlink_metadata(&path)
    .map(|metadata| metadata.file_type().is_symlink())
    .unwrap_or(false)
  {
    return Err("recusando alterar um hypridle.conf simbólico".into());
  }

  let content = if path.exists() {
    fs::read_to_string(&path).map_err(|error| error.to_string())?
  } else {
    DEFAULT_HYPRIDLE_CONF.to_string()
  };

  let previous = listener_minutes_from(&content, matches).unwrap_or(0);
  let updated = if minutes == 0 {
    remove_listener(&content, matches)
  } else {
    match setter(&content, minutes) {
      Ok(rewritten) => rewritten,
      Err(_) => listener_template(&content, minutes),
    }
  };
  let tmp = path.with_extension("tmp");
  fs::write(&tmp, updated).map_err(|error| error.to_string())?;
  fs::rename(&tmp, &path).map_err(|error| error.to_string())?;

  restart_hypridle();

  Ok(previous)
}

/// Writes a new DPMS timeout back to the ARGVUS hypridle config. Returns the
/// previous timeout when the change was applied.
pub fn apply_screen_off_minutes(minutes: u32) -> Result<u32, String> {
  apply_listener_minutes(
    minutes,
    calls_dpms_off,
    set_screen_off_minutes,
    with_screen_off_listener,
  )
}

/// Writes a new screen-lock timeout back to the ARGVUS hypridle config. Returns
/// the previous timeout when the change was applied.
pub fn apply_lock_minutes(minutes: u32) -> Result<u32, String> {
  apply_listener_minutes(minutes, calls_lock, set_lock_minutes, with_lock_listener)
}

/// Defines the constant `RESTART_DEBOUNCE`. Its explicit shape preserves the contract consumed by the rest of the workspace and keeps the intent visible as the module evolves.
const RESTART_DEBOUNCE: Duration = Duration::from_millis(800);

/// Maintains the static state `RESTART_REQUEST`. Its explicit shape preserves the contract consumed by the rest of the workspace and keeps the intent visible as the module evolves.
static RESTART_REQUEST: OnceLock<Mutex<Option<mpsc::Sender<()>>>> = OnceLock::new();

/// Restarts the running hypridle through the ARGVUS session wrapper. Rapid
/// changes are coalesced into a single restart once they settle, and systemd's
/// start rate-limiter is cleared first so a burst of changes cannot drop the
/// service into the `start-limit-hit` failed state.
fn restart_hypridle() {
  let mut guard = RESTART_REQUEST
    .get_or_init(|| Mutex::new(None))
    .lock()
    .unwrap_or_else(std::sync::PoisonError::into_inner);
  let Some(sender) = guard.as_ref() else {
    let (sender, receiver) = mpsc::channel::<()>();
    *guard = Some(sender.clone());
    drop(guard);
    std::thread::Builder::new()
      .name("hypridle-restart".to_string())
      .spawn(move || hypridle_restart_worker(receiver))
      .expect("failed to spawn the hypridle restart worker");
    let _ = sender.send(());
    return;
  };
  let _ = sender.send(());
}

/// Executes the `hypridle_restart_worker` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
fn hypridle_restart_worker(receiver: mpsc::Receiver<()>) {
  loop {
    match receiver.recv_timeout(RESTART_DEBOUNCE) {
      Err(mpsc::RecvTimeoutError::Disconnected) => break,
      Err(mpsc::RecvTimeoutError::Timeout) => continue,
      Ok(()) => {
        while matches!(receiver.recv_timeout(RESTART_DEBOUNCE), Ok(())) {}
        restart_hypridle_now();
      }
    }
  }
}

/// Executes the `restart_hypridle_now` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
fn restart_hypridle_now() {
  use std::process::Command;
  let _ = Command::new("systemctl")
    .args(["--user", "reset-failed", "argvus-hypridle.service"])
    .status();
  let _ = Command::new("argvus-sessionctl")
    .args(["restart", "hypridle"])
    .status();
}

/// Extracts the timeout (in minutes) of the listener whose `on-timeout`
/// matches `matches`, reading `timeout = 0` as disabled.
fn listener_minutes_from(content: &str, matches: fn(&str) -> bool) -> Option<u32> {
  let target = find_listener_timeout(content, matches)?;
  content
    .lines()
    .enumerate()
    .filter(|(index, line)| {
      *index == target && line.trim_start().starts_with("timeout") && line.contains('=')
    })
    .map(|(_, line)| {
      line
        .split_once('=')
        .and_then(|(_, value)| value.trim().parse::<u32>().ok())
    })
    .next()
    .flatten()
    .and_then(|seconds| (seconds > 0).then(|| (seconds / 60).max(1)))
}

/// Locates the `timeout =` line that precedes the listener whose `on-timeout`
/// matches `matches`, which flags the listener this module manages.
fn find_listener_timeout(content: &str, matches: fn(&str) -> bool) -> Option<usize> {
  let mut current_timeout: Option<usize> = None;
  let mut target: Option<usize> = None;
  for (index, line) in content.lines().enumerate() {
    let trimmed = line.trim();
    if trimmed.starts_with('#') || trimmed.is_empty() {
      continue;
    }
    if trimmed.starts_with("timeout") && trimmed.contains('=') {
      current_timeout = Some(index);
    } else if trimmed.starts_with("on-timeout") && trimmed.contains('=') {
      let value = trimmed
        .split_once('=')
        .map(|(_, value)| value)
        .unwrap_or("");
      let value = value.trim();
      if matches(value) {
        target = current_timeout;
      }
      current_timeout = None;
    }
  }
  target
}

/// Executes the `calls_dpms_off` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
fn calls_dpms_off(value: &str) -> bool {
  let compact: String = value
    .chars()
    .filter(|character| !character.is_whitespace())
    .collect::<String>()
    .to_ascii_lowercase();
  compact.contains("dpmsoff")
    || compact.contains("dpms_state")
    || compact.contains("dpms,off")
    || compact.contains("hl.dsp.dpms({action=\"off\"")
}

/// Whether an `on-timeout` value is a screen-lock command.
fn calls_lock(value: &str) -> bool {
  let compact: String = value
    .chars()
    .filter(|character| !character.is_whitespace())
    .collect::<String>()
    .to_ascii_lowercase();
  compact.contains("lock")
}

/// The screen-lock command to reuse, taken from the config's `general.lock_cmd`
/// when available, with the ARGVUS default as a fallback.
fn lock_command(content: &str) -> String {
  content
    .lines()
    .find_map(|line| {
      let trimmed = line.trim();
      if trimmed.starts_with('#') {
        return None;
      }
      let (name, value) = trimmed.split_once('=')?;
      (name.trim() == "lock_cmd").then(|| value.trim().to_string())
    })
    .unwrap_or_else(|| "sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock".to_string())
}

#[cfg(test)]
/// Executes the `screen_off_minutes_from` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
fn screen_off_minutes_from(content: &str) -> Option<u32> {
  listener_minutes_from(content, calls_dpms_off)
}

#[cfg(test)]
/// Executes the `lock_minutes_from` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
fn lock_minutes_from(content: &str) -> Option<u32> {
  listener_minutes_from(content, calls_lock)
}

#[cfg(test)]
mod tests {
  use super::*;

  /// Defines the constant `SAMPLE`. Its explicit shape preserves the contract consumed by the rest of the workspace and keeps the intent visible as the module evolves.
  const SAMPLE: &str = "\
# ARGVUS idle
timeout = 300
onetime = false
label = dpms
on-timeout = hyprctl dispatch dpms off
on-resume = hyprctl dispatch dpms on

timeout = 1800
onetime = false
label = suspend
on-timeout = systemctl suspend
";

  #[test]
  /// Executes the `finds_the_dpms_listener_timeout` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn finds_the_dpms_listener_timeout() {
    assert_eq!(listener_minutes_from(SAMPLE, calls_dpms_off), Some(5));
  }

  #[test]
  /// Executes the `finds_the_lock_listener_timeout` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn finds_the_lock_listener_timeout() {
    let config = "\
general {
  lock_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}

listener {
  timeout = 900
  on-timeout = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch dpms off
}
";
    assert_eq!(lock_minutes_from(config), Some(15));
    let updated = set_lock_minutes(config, 10).unwrap();
    assert_eq!(lock_minutes_from(&updated), Some(10));
    assert!(updated.contains("timeout = 300"), "{updated}");
    assert_eq!(listener_minutes_from(&updated, calls_dpms_off), Some(5));
  }

  #[test]
  /// Executes the `rewrites_only_the_dpms_timeout` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn rewrites_only_the_dpms_timeout() {
    let updated = set_screen_off_minutes(SAMPLE, 30).unwrap();
    assert!(updated.contains("# ARGVUS idle"), "{updated}");
    assert!(updated.contains("timeout = 1800\n"), "{updated}");
    assert!(updated.contains("systemctl suspend"), "{updated}");
    assert!(!updated.contains("timeout = 300\n"), "{updated}");
    assert_eq!(screen_off_minutes_from(&updated), Some(30));
  }

  #[test]
  /// Executes the `recognizes_an_off_idiom_without_an_installer` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn recognizes_an_off_idiom_without_an_installer() {
    assert!(calls_dpms_off("hyprctl dispatch dpms off"));
    assert!(calls_dpms_off("hyprctl dispatch dpms_state 0"));
    assert!(!calls_dpms_off("systemctl suspend"));
    assert!(!calls_dpms_off("hyprctl dispatch dpms on"));
    assert!(calls_dpms_off(
      "hyprctl dispatch 'hl.dsp.dpms({ action = \"off\" })'"
    ));
    assert!(!calls_dpms_off(
      "hyprctl dispatch 'hl.dsp.dpms({ action = \"on\" })'"
    ));
  }

  #[test]
  /// Executes the `refuses_configs_without_a_dpms_listener` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn refuses_configs_without_a_dpms_listener() {
    let idle_only = "\
timeout = 1800
onetime = false
on-timeout = systemctl suspend
";
    assert!(set_screen_off_minutes(idle_only, 10).is_err());
    assert!(screen_off_minutes_from(idle_only).is_none());
  }

  #[test]
  /// Executes the `adds_a_dpms_listener_when_missing` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn adds_a_dpms_listener_when_missing() {
    let stock = "\
general {
  lock_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}

listener {
  timeout = 900
  on-timeout = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}
";
    assert_eq!(screen_off_minutes_from(stock), None);
    let updated = with_screen_off_listener(stock, 1);
    assert_eq!(screen_off_minutes_from(&updated), Some(1));
    assert!(updated.contains("timeout = 900"), "{updated}");
    assert!(
      updated.contains("on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = \"off\" })'"),
      "{updated}"
    );
    assert!(!updated.contains("Screen-off timer"), "{updated}");
  }

  #[test]
  /// Executes the `removing_the_dpms_listener_disables_screen_off` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn removing_the_dpms_listener_disables_screen_off() {
    let config = "\
general {
  lock_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}

listener {
  timeout = 1
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 1800
  on-timeout = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}
";
    assert_eq!(screen_off_minutes_from(config), Some(1));
    let updated = remove_listener(config, calls_dpms_off);
    assert_eq!(screen_off_minutes_from(&updated), None);
    assert!(updated.contains("general {"), "{updated}");
    assert!(updated.contains("timeout = 1800"), "{updated}");
    assert!(!updated.contains("dpms off"), "{updated}");
  }

  #[test]
  /// Executes the `a_zero_timeout_reads_as_disabled` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn a_zero_timeout_reads_as_disabled() {
    let content = "timeout = 0\non-timeout = hyprctl dispatch dpms off\n";
    assert_eq!(screen_off_minutes_from(content), None);
  }

  #[test]
  /// Executes the `adds_a_lock_listener_when_missing` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn adds_a_lock_listener_when_missing() {
    let bare = "\
listener {
  timeout = 300
  on-timeout = hyprctl dispatch dpms off
}
";
    assert_eq!(lock_minutes_from(bare), None);
    let updated = with_lock_listener(bare, 1);
    assert_eq!(lock_minutes_from(&updated), Some(1));
    assert!(updated.contains("timeout = 300"), "{updated}");
    assert!(!updated.contains("Screen-lock timer"), "{updated}");
    assert_eq!(listener_minutes_from(&updated, calls_dpms_off), Some(5));
  }

  #[test]
  /// Executes the `lock_listener_reuses_the_configured_lock_command` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn lock_listener_reuses_the_configured_lock_command() {
    let config = "\
general {
  lock_cmd = custom-locker --damp
}

listener {
  timeout = 900
  on-timeout = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}
";
    assert_eq!(lock_command(config), "custom-locker --damp");
    let updated = with_lock_listener(config, 5);
    assert!(
      updated.contains("on-timeout = custom-locker --damp"),
      "{updated}"
    );
    assert_eq!(lock_minutes_from(&updated), Some(5));
  }

  #[test]
  /// Executes the `removing_the_lock_listener_disables_lock` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn removing_the_lock_listener_disables_lock() {
    let config = "\
general {
  lock_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch dpms off
}

listener {
  timeout = 900
  on-timeout = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock
}
";
    assert_eq!(lock_minutes_from(config), Some(15));
    let updated = remove_listener(config, calls_lock);
    assert_eq!(lock_minutes_from(&updated), None);
    assert_eq!(listener_minutes_from(&updated, calls_dpms_off), Some(5));
    assert!(
      updated.contains("lock_cmd = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock"),
      "{updated}"
    );
    assert!(
      !updated.contains("on-timeout = sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock"),
      "{updated}"
    );
  }

  #[test]
  /// Executes the `calls_lock_matches_lock_idioms_but_not_sleep_or_dpms` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn calls_lock_matches_lock_idioms_but_not_sleep_or_dpms() {
    assert!(calls_lock(
      "sh /usr/share/argvus/power/sh/hypr-power-menu.sh --lock"
    ));
    assert!(calls_lock("swaylock"));
    assert!(!calls_lock("systemctl suspend"));
    assert!(!calls_lock("hyprctl dispatch dpms off"));
  }

  #[test]
  /// Executes the `only_removes_blocks_named_listener` step in this module. The behavior is encapsulated here so callers depend on a clear domain decision instead of duplicating system or UI details.
  fn only_removes_blocks_named_listener() {
    let config = "\
listen {
  timeout = 900
  on-timeout = sh loginctl lock-session
}
";
    assert_eq!(lock_minutes_from(config), Some(15));
    let updated = remove_listener(config, calls_lock);
    assert_eq!(updated, config, "{updated}");
  }
}
