use argvus_control_center_core::paths::argvus_config_home;
use std::fs;
use std::path::PathBuf;
use std::sync::{mpsc, Mutex, OnceLock};
use std::time::Duration;

/// The ARGVUS hypridle configuration lives under the user config path.
/// This matches the path resolved by `paths_config hypr/hypridle.conf` when
/// ARGVUS_MUTABLE_CONFIG=1 (used by argvus-session and argvus-power scripts).
pub fn config_path() -> PathBuf {
  argvus_config_home().join("hypr/hypridle.conf")
}

const DEFAULT_HYPRIDLE_CONF: &str = r#"# ARGVUS hypridle configuration
# Generated by ARGVUS Control Center

general {
  lock_cmd = sh /usr/share/argvus/scripts/apps/hypr-power-menu.sh --lock
  before_sleep_cmd = sh /usr/share/argvus/scripts/apps/hypr-power-menu.sh --lock
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}
"#;

/// Returns the screen-off idle timeout in whole minutes.
pub fn screen_off_minutes() -> Option<u32> {
  let path = config_path();
  let content = fs::read_to_string(path).ok()?;
  screen_off_minutes_from(&content)
}

/// Updates the timeout that feeds the DPMS-off listener in `content` and
/// returns the new full configuration text. Returns an error when the config
/// has no recognizable DPMS listener, so we never guess at foreign layouts.
pub fn set_screen_off_minutes(content: &str, minutes: u32) -> Result<String, String> {
  let target = find_dpms_timeout(content).ok_or_else(|| {
    "O hypridle do ARGVUS não define um listener de desligar tela; nada foi alterado.".to_string()
  })?;
  let new_seconds = minutes.saturating_mul(60);
  let mut updated = String::with_capacity(content.len());
  for (index, line) in content.lines().enumerate() {
    if index == target {
      let indent: String = line
        .chars()
        .take_while(|character| character.is_whitespace())
        .collect();
      updated.push_str(&format!("{indent}timeout = {new_seconds}\n"));
    } else {
      updated.push_str(line);
      updated.push('\n');
    }
  }
  Ok(updated)
}

/// Builds a config by appending an active DPMS-off listener. Used when the
/// existing config has no recognizable screen-off listener (the stock ARGVUS
/// config ships with that example commented out), preserving everything else
/// such as the inactivity-lock listener.
fn with_screen_off_listener(content: &str, minutes: u32) -> String {
  let seconds = minutes.saturating_mul(60);
  let base = content.trim_end_matches(['\r', '\n']).to_string();
  format!(
    "{base}\n\n# Screen-off timer (managed by ARGVUS Control Center)\nlistener {{\n  timeout = {seconds}\n  on-timeout = hyprctl dispatch dpms off\n  on-resume = hyprctl dispatch dpms on\n}}\n"
  )
}

/// Removes the listener block that turns the screen off, disabling auto
/// screen-off (the "never" option) while preserving every other listener.
fn remove_screen_off_listener(content: &str) -> String {
  let pieces: Vec<&str> = content.split_inclusive('\n').collect();
  let mut drop = vec![false; pieces.len()];
  let mut in_listener = false;
  let mut has_dpms = false;
  let mut start = 0;
  for (index, piece) in pieces.iter().enumerate() {
    let trimmed = piece.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') {
      continue;
    }
    if !in_listener && trimmed.starts_with("listener") && trimmed.ends_with('{') {
      in_listener = true;
      has_dpms = false;
      start = index;
      continue;
    }
    if in_listener {
      if trimmed.starts_with("on-timeout") && calls_dpms_off(trimmed) {
        has_dpms = true;
      }
      if trimmed.ends_with('}') {
        if has_dpms {
          for line in &mut drop[start..=index] {
            *line = true;
          }
        }
        in_listener = false;
      }
    }
  }
  pieces
    .into_iter()
    .zip(drop)
    .filter_map(|(piece, remove)| (!remove).then_some(piece))
    .collect()
}

/// Writes a new DPMS timeout back to the ARGVUS hypridle config. Returns the
/// previous timeout when the change was applied.
pub fn apply_screen_off_minutes(minutes: u32) -> Result<u32, String> {
  let path = config_path();

  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent).map_err(|e| e.to_string())?;
  }

  if fs::symlink_metadata(&path)
    .map(|metadata| metadata.file_type().is_symlink())
    .unwrap_or(false)
  {
    return Err("recusando alterar um hypridle.conf simbólico".into());
  }

  let content = if path.exists() {
    fs::read_to_string(&path).map_err(|error| error.to_string())?
  } else {
    DEFAULT_HYPRIDLE_CONF.to_string()
  };

  let previous = screen_off_minutes_from(&content).unwrap_or(0);
  let updated = if minutes == 0 {
    remove_screen_off_listener(&content)
  } else {
    match set_screen_off_minutes(&content, minutes) {
      Ok(rewritten) => rewritten,
      Err(_) => with_screen_off_listener(&content, minutes),
    }
  };
  let tmp = path.with_extension("tmp");
  fs::write(&tmp, updated).map_err(|error| error.to_string())?;
  fs::rename(&tmp, &path).map_err(|error| error.to_string())?;

  restart_hypridle();

  Ok(previous)
}

const RESTART_DEBOUNCE: Duration = Duration::from_millis(800);

static RESTART_REQUEST: OnceLock<Mutex<Option<mpsc::Sender<()>>>> = OnceLock::new();

/// Restarts the running hypridle through the ARGVUS session wrapper. Rapid
/// changes are coalesced into a single restart once they settle, and systemd's
/// start rate-limiter is cleared first so a burst of changes cannot drop the
/// service into the `start-limit-hit` failed state.
fn restart_hypridle() {
  let mut guard = RESTART_REQUEST
    .get_or_init(|| Mutex::new(None))
    .lock()
    .unwrap_or_else(std::sync::PoisonError::into_inner);
  let Some(sender) = guard.as_ref() else {
    let (sender, receiver) = mpsc::channel::<()>();
    *guard = Some(sender.clone());
    drop(guard);
    std::thread::Builder::new()
      .name("hypridle-restart".to_string())
      .spawn(move || hypridle_restart_worker(receiver))
      .expect("failed to spawn the hypridle restart worker");
    let _ = sender.send(());
    return;
  };
  let _ = sender.send(());
}

fn hypridle_restart_worker(receiver: mpsc::Receiver<()>) {
  loop {
    match receiver.recv_timeout(RESTART_DEBOUNCE) {
      Err(mpsc::RecvTimeoutError::Disconnected) => break,
      Err(mpsc::RecvTimeoutError::Timeout) => continue,
      Ok(()) => {
        while matches!(receiver.recv_timeout(RESTART_DEBOUNCE), Ok(())) {}
        restart_hypridle_now();
      }
    }
  }
}

fn restart_hypridle_now() {
  use std::process::Command;
  let _ = Command::new("systemctl")
    .args(["--user", "reset-failed", "argvus-hypridle.service"])
    .status();
  let _ = Command::new("argvus-sessionctl")
    .args(["restart", "hypridle"])
    .status();
}

fn screen_off_minutes_from(content: &str) -> Option<u32> {
  let target = find_dpms_timeout(content)?;
  content
    .lines()
    .enumerate()
    .filter(|(index, line)| {
      *index == target && line.trim_start().starts_with("timeout") && line.contains('=')
    })
    .map(|(_, line)| {
      line
        .split_once('=')
        .and_then(|(_, value)| value.trim().parse::<u32>().ok())
    })
    .next()
    .flatten()
    .and_then(|seconds| (seconds > 0).then(|| (seconds / 60).max(1)))
}

/// Locates the `timeout =` line that precedes a `hyprctl ... dpms off`
/// listener, which is hypridle's canonical screen-off idiom.
fn find_dpms_timeout(content: &str) -> Option<usize> {
  let mut current_timeout: Option<usize> = None;
  let mut target: Option<usize> = None;
  for (index, line) in content.lines().enumerate() {
    let trimmed = line.trim();
    if trimmed.starts_with('#') || trimmed.is_empty() {
      continue;
    }
    if trimmed.starts_with("timeout") && trimmed.contains('=') {
      current_timeout = Some(index);
    } else if trimmed.starts_with("on-timeout") && trimmed.contains('=') {
      let value = trimmed
        .split_once('=')
        .map(|(_, value)| value)
        .unwrap_or("");
      let value = value.trim();
      if calls_dpms_off(value) {
        target = current_timeout;
      }
      current_timeout = None;
    }
  }
  target
}

fn calls_dpms_off(value: &str) -> bool {
  let compact: String = value
    .chars()
    .filter(|character| !character.is_whitespace())
    .collect::<String>()
    .to_ascii_lowercase();
  compact.contains("dpmsoff") || compact.contains("dpms_state") || compact.contains("dpms,off")
}

#[cfg(test)]
mod tests {
  use super::*;

  const SAMPLE: &str = "\
# ARGVUS idle
timeout = 300
onetime = false
label = dpms
on-timeout = hyprctl dispatch dpms off
on-resume = hyprctl dispatch dpms on

timeout = 1800
onetime = false
label = suspend
on-timeout = systemctl suspend
";

  #[test]
  fn finds_the_dpms_listener_timeout() {
    assert_eq!(screen_off_minutes_from(SAMPLE), Some(5));
  }

  #[test]
  fn rewrites_only_the_dpms_timeout() {
    let updated = set_screen_off_minutes(SAMPLE, 30).unwrap();
    assert!(updated.contains("# ARGVUS idle"), "{updated}");
    assert!(updated.contains("timeout = 1800\n"), "{updated}");
    assert!(updated.contains("systemctl suspend"), "{updated}");
    assert!(!updated.contains("timeout = 300\n"), "{updated}");
    assert_eq!(screen_off_minutes_from(&updated), Some(30));
  }

  #[test]
  fn recognizes_an_off_idiom_without_an_installer() {
    assert!(calls_dpms_off("hyprctl dispatch dpms off"));
    assert!(calls_dpms_off("hyprctl dispatch dpms_state 0"));
    assert!(!calls_dpms_off("systemctl suspend"));
    assert!(!calls_dpms_off("hyprctl dispatch dpms on"));
  }

  #[test]
  fn refuses_configs_without_a_dpms_listener() {
    let idle_only = "\
timeout = 1800
onetime = false
on-timeout = systemctl suspend
";
    assert!(set_screen_off_minutes(idle_only, 10).is_err());
    assert!(screen_off_minutes_from(idle_only).is_none());
  }

  #[test]
  fn adds_a_dpms_listener_when_missing() {
    let stock = "\
general {
  lock_cmd = sh /usr/share/argvus/scripts/apps/hypr-power-menu.sh --lock
}

listener {
  timeout = 900
  on-timeout = sh /usr/share/argvus/scripts/apps/hypr-power-menu.sh --lock
}
";
    assert_eq!(screen_off_minutes_from(stock), None);
    let updated = with_screen_off_listener(stock, 1);
    assert_eq!(screen_off_minutes_from(&updated), Some(1));
    assert!(updated.contains("timeout = 900"), "{updated}");
    assert!(updated.contains("on-timeout = hyprctl dispatch dpms off"), "{updated}");
  }

  #[test]
  fn removing_the_dpms_listener_disables_screen_off() {
    let config = "\
general {
  lock_cmd = sh /usr/share/argvus/scripts/apps/hypr-power-menu.sh --lock
}

listener {
  timeout = 1
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 1800
  on-timeout = sh /usr/share/argvus/scripts/apps/hypr-power-menu.sh --lock
}
";
    assert_eq!(screen_off_minutes_from(config), Some(1));
    let updated = remove_screen_off_listener(config);
    assert_eq!(screen_off_minutes_from(&updated), None);
    assert!(updated.contains("general {"), "{updated}");
    assert!(updated.contains("timeout = 1800"), "{updated}");
    assert!(!updated.contains("dpms off"), "{updated}");
  }

  #[test]
  fn a_zero_timeout_reads_as_disabled() {
    let content = "timeout = 0\non-timeout = hyprctl dispatch dpms off\n";
    assert_eq!(screen_off_minutes_from(content), None);
  }
}